name: Build and Upload JAR

on:
  push:
    branches:
      - master  # or main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # use '23' only if you're sure you need Java 23 and it's supported

      - name: Build with Maven
        run: mvn clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: stream-client-jar
          path: target/*.jar
